# Generated by Django 2.1.2 on 2018-10-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='map_code',
        ),
        migrations.AddField(
            model_name='event',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
