# Generated by Django 2.1.2 on 2018-10-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181026_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='map_url',
            new_name='venue_map_url',
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
